replicaCount: 1
image:
  repository: yasminkloub1994/udaconnect-api-gateway
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 5002
imagePullSecrets: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  DATABASE_URL: postgresql://udaconnect:udaconnect@postgres:5432/udaconnect
  PYTHONPATH: "/app"
  FLASK_RUN_HOST: "0.0.0.0"
  FLASK_RUN_PORT: "5002"
  PERSONS_URL: "http://persons:5000"
  LOCATIONS_URL: "http://locations:5001"
  CONNECTIONS_URL: "http://connections:5003"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
